const QUESTIONS = [
  { section:'Where are you?', text:'When you think about what comes next, which feels most like you?', category:'state' },
  { section:'Knowing yourself', text:'How well do you feel you know yourself?', category:'state' },
  { section:'Exploring', text:'When something catches your interest, what usually happens?', category:'state' },
  { section:'What feels hard', text:'When you think about your future, what feels hardest right now?', category:'state' },
  { section:'Exploring', text:'How much have you actually explored the things you are curious about?', category:'state' },
  { section:'Deciding', text:'When you are unsure about an important choice, what do you tend to do?', category:'state' },
  { section:'Where you are today', text:'Which feels closest to you right now?', category:'state' },
  { section:'Next month', text:'If you had the next month to make progress on your future, what would you most want to do?', category:'state' }
];
const ENQUIRY_EMAIL = process.env.ENQUIRY_EMAIL || 'enquire@theevolvefoundation.com';
const MAIL_FROM = process.env.MAIL_FROM || 'The Evolve Foundation <enquire@theevolvefoundation.com>';
const ALLOWED_ORIGIN = process.env.ALLOWED_ORIGIN || '';
const attempts = globalThis.__studentCompassAttempts || new Map();
globalThis.__studentCompassAttempts = attempts;
function rateLimit(ip){const now=Date.now(), windowMs=60*60*1000, max=5, record=attempts.get(ip); if(!record||now-record.start>windowMs){attempts.set(ip,{start:now,count:1});return true;} record.count+=1;return record.count<=max;}
function escapeHtml(value){return String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');}
function getState(answers){const scores={bearings:0,exploring:0,direction:0,moving:0};const map=[['bearings','exploring','direction','moving'],['bearings','exploring','direction','moving'],['bearings','exploring','exploring','moving'],['bearings','exploring','direction','moving'],['bearings','exploring','direction','moving'],['bearings','exploring','direction','moving'],['bearings','exploring','direction','moving'],['bearings','exploring','direction','moving']];answers.forEach((v,i)=>{if(map[i]?.[v])scores[map[i][v]]++;});return Object.keys(scores).sort((a,b)=>scores[b]-scores[a])[0]||'bearings';}
const STATES={bearings:{title:'Finding Your Bearings',summary:"You're still figuring out what fits you and what matters to you. That is a perfectly useful place to be.",stepTitle:'Start with yourself',step:'Spend a little time noticing what you naturally enjoy, what you do well and what brings out your best.',launch:'If you want guided support to understand yourself better, Launchpad can help you start there.'},exploring:{title:'Looking Around',summary:'You have some interests and possibilities in mind, but you need more experience to know which ones are worth exploring.',stepTitle:'Explore one thing',step:'Pick one thing you are curious about. Talk to someone, try something small or find a real experience that lets you learn more about it.',launch:'If you want a structured space to explore yourself and possible directions, Launchpad can help.'},direction:{title:'Finding a Direction',summary:'You have something in mind, but you are still working out whether it is a direction worth pursuing.',stepTitle:'Test before you decide',step:'Choose one small way to learn more about the direction. Look for evidence from people, experiences or experiments rather than trying to predict the whole future.',launch:'If you want help turning a possible direction into a thoughtful decision, Launchpad is designed for that.'},moving:{title:'Ready to Move',summary:'You have a direction in mind. The useful question now is not “Is this definitely right?” but “What can I do next to learn more?”',stepTitle:'Take one concrete step',step:'Choose one action you can complete in the next 30 days. Do it, notice what you learn and adjust from there.',launch:'You may not need a programme right now. If you want structured accountability and reflection, Launchpad is there when you need it.'}};
function buildStudentEmail(name,state){const s=STATES[state];return `<div style="font-family:Arial,sans-serif;line-height:1.6;color:#17231f;max-width:680px;margin:0 auto;padding:32px 20px;"><p style="font-size:12px;letter-spacing:.14em;text-transform:uppercase;color:#B87A2E;">STUDENT COMPASS</p><h1 style="font-family:Georgia,serif;font-weight:500;font-size:34px;line-height:1.15;">${escapeHtml(name)}, here is where you seem to be right now.</h1><p style="font-size:18px;">${escapeHtml(s.summary)}</p><div style="margin:28px 0;padding:22px;border:1px solid #ddd8ce;background:#FBFAF7;"><p style="margin:0 0 6px;font-size:12px;letter-spacing:.12em;text-transform:uppercase;color:#5C8A7E;">Your starting point</p><h2 style="font-family:Georgia,serif;font-weight:500;margin:0 0 10px;font-size:26px;">${escapeHtml(s.title)}</h2><p style="margin:0 0 12px;">Your next step: <strong>${escapeHtml(s.stepTitle)}</strong></p><p style="margin:0;">${escapeHtml(s.step)}</p></div><p>You don't need to have everything figured out. Use this as a starting point, not a label.</p><p style="margin-top:28px;"><a href="https://www.theevolvefoundation.com/launchpad.html" style="display:inline-block;padding:12px 20px;background:#B87A2E;color:#fff;text-decoration:none;font-weight:600;">Explore Launchpad →</a></p><p style="margin-top:30px;color:#52605a;">Helping young people understand themselves and navigate life well</p><p style="font-size:13px;color:#6a746f;">Warmly,<br><strong>Rams</strong><br>The Evolve Foundation · India</p></div>`;}
function buildNotificationEmail(lead,state,answers){const s=STATES[state];const rows=QUESTIONS.map((q,i)=>`<tr><td style="padding:7px;border-bottom:1px solid #eee;">${i+1}</td><td style="padding:7px;border-bottom:1px solid #eee;">${escapeHtml(q.text)}</td><td style="padding:7px;border-bottom:1px solid #eee;text-align:center;">${answers[i]+1}</td></tr>`).join('');return `<div style="font-family:Arial,sans-serif;line-height:1.5;color:#17231f;max-width:800px;"><h2>New Student Compass lead</h2><p><strong>Name:</strong> ${escapeHtml(lead.name)}<br><strong>Email:</strong> ${escapeHtml(lead.email)}<br><strong>Phone:</strong> ${escapeHtml(lead.phone)}<br><strong>Captured:</strong> ${escapeHtml(lead.capturedAt)}</p><h3>Compass state</h3><p><strong>${escapeHtml(s.title)}</strong> — ${escapeHtml(s.summary)}</p><h3>Responses</h3><table style="border-collapse:collapse;width:100%;font-size:13px;"><thead><tr><th style="text-align:left;padding:7px;border-bottom:2px solid #ccc;">#</th><th style="text-align:left;padding:7px;border-bottom:2px solid #ccc;">Reflection</th><th style="padding:7px;border-bottom:2px solid #ccc;">Answer</th></tr></thead><tbody>${rows}</tbody></table></div>`;}
async function sendResendEmail({to,subject,html,replyTo,idempotencyKey}){const apiKey=process.env.RESEND_API_KEY;if(!apiKey)throw new Error('RESEND_API_KEY is not configured.');const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${apiKey}`,'Content-Type':'application/json',...(idempotencyKey?{'Idempotency-Key':idempotencyKey}:{})},body:JSON.stringify({from:MAIL_FROM,to:[to],subject,html,reply_to:replyTo})});if(!response.ok){const body=await response.text();throw new Error(`Resend error ${response.status}: ${body}`);}return response.json();}
module.exports=async function handler(req,res){const origin=req.headers.origin||'';if(ALLOWED_ORIGIN&&origin&&origin!==ALLOWED_ORIGIN)return res.status(403).json({ok:false,message:'Origin not allowed.'});res.setHeader('Access-Control-Allow-Origin',ALLOWED_ORIGIN||origin||'*');res.setHeader('Access-Control-Allow-Methods','POST, OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type');if(req.method==='OPTIONS')return res.status(204).end();if(req.method!=='POST')return res.status(405).json({ok:false,message:'Method not allowed.'});try{const ip=req.headers['x-forwarded-for']?.split(',')[0]?.trim()||req.socket?.remoteAddress||'unknown';if(!rateLimit(ip))return res.status(429).json({ok:false,message:'Too many submissions. Please try again later.'});const body=typeof req.body==='string'?JSON.parse(req.body):(req.body||{});const {name,email,phone,answers,website}=body;if(website)return res.status(400).json({ok:false,message:'Invalid submission.'});const cleanName=String(name||'').trim(),cleanEmail=String(email||'').trim().toLowerCase(),cleanPhone=String(phone||'').trim();if(!cleanName||cleanName.length>120)return res.status(400).json({ok:false,message:'Please enter your name.'});if(!/^\S+@\S+\.\S+$/.test(cleanEmail)||cleanEmail.length>180)return res.status(400).json({ok:false,message:'Please enter a valid email address.'});if(!cleanPhone||cleanPhone.length>40)return res.status(400).json({ok:false,message:'Please enter your phone number.'});if(!Array.isArray(answers)||answers.length!==8||answers.some(v=>!Number.isInteger(Number(v))||Number(v)<0||Number(v)>3))return res.status(400).json({ok:false,message:'Please complete all eight reflections before continuing.'});const values=answers.map(Number),state=getState(values),capturedAt=new Date().toISOString(),lead={name:cleanName,email:cleanEmail,phone:cleanPhone,capturedAt},submissionId=String(body.submissionId||`${Date.now()}-${Math.random().toString(36).slice(2)}`).replace(/[^a-zA-Z0-9_-]/g,'').slice(0,100);await Promise.all([sendResendEmail({to:cleanEmail,replyTo:ENQUIRY_EMAIL,subject:'Your Student Compass — The Evolve Foundation',html:buildStudentEmail(cleanName,state),idempotencyKey:`student-compass-student-${submissionId}`}),sendResendEmail({to:ENQUIRY_EMAIL,replyTo:cleanEmail,subject:`New Student Compass lead — ${cleanName}`,html:buildNotificationEmail(lead,state,values),idempotencyKey:`student-compass-lead-${submissionId}`})]);return res.status(200).json({ok:true,state});}catch(error){console.error('Student Compass submission failed:',error);return res.status(500).json({ok:false,message:'We could not send your reflection just now. Please try again in a moment.'});}};
